### ISSUE TITLE
"not connecting" d-rats at startup

### ISSUE THREAD

**Issue by maurizioandreotti** [wb8tyw/D-Rats#127] opened 2022-03-26 10:42 UTC
while I tested that fork on the connection 
I got a drats / python "not responding" and had to kill it via control panel.
I guess something happened to the config file or the file with the list of stations.

today at startup, i am getting a "not connecting" d-rats

mauri@T450-Maurizio MINGW64 ~/D-Rats-python3_tyw
$ python3 ./d-rats.py --loglevel DEBUG
03/26/2022 10:03:44:INFO:D-Rats:main: re-config option found -- Reconfigure D-rats
03/26/2022 10:03:44:INFO:Mainapp:Enabled debug log for Win32 systems
03/26/2022 10:03:44:INFO:Version:HTTP_CLIENT_HEADERS={'User-Agent': 'd-rats/0.4.00 pre-release 1'}
03/26/2022 10:03:44:INFO:QST:FeedParser not available
03/26/2022 10:03:45:INFO:DratsConfig:File C:/Users/mauri/AppData/Roaming/D-RATS-EV/d-rats.config
03/26/2022 10:03:45:INFO:MainApp:_refresh_lang: Loading locale `it'
03/26/2022 10:03:45:INFO:MainApp:_refresh_lang: Locale dir is: C:/msys64/home/mauri/D-Rats-python3_tyw/locale
03/26/2022 10:03:45:ERROR:MainApp:_refresh_lang: Messages catalog file missing  for it.  Need to use 'msgfmt tool to generate.
03/26/2022 10:03:45:INFO:MainApp:D-RATS v0.4.00 pre-release 1 starting at Sat Mar 26 10:03:45 2022 on Platform Win32Platform:
  base:       C:/Users/mauri/AppData/Roaming/D-RATS-EV
  source_dir: C:/msys64/home/mauri/D-Rats-python3_tyw
  OS version: Windows 10 (10, 0, 19041, 2, '')
03/26/2022 10:03:45:INFO:MainApp:load position from config file
03/26/2022 10:03:45:INFO:MainApp:_static_gps: Configuring the Static position: 45.800456,9.428377
03/26/2022 10:03:45:INFO:MainApp:_static_gps: Mapserver active: True ca;; IZ2LXI
03/26/2022 10:03:45:INFO:MainApp:preparing our gpsfix in JSON :{ "lat": "45.800456", "lng": "9.428377", "station": "IZ2LXI", "comments": "altitude: 0","timestamp": "2022-03-26 09:03:45"  }
03/26/2022 10:03:45:INFO:MainApp:Socket Created
03/26/2022 10:03:45:INFO:MainApp:Connecting to: localhost:9500

(d-rats.py:1776): GLib-GIO-WARNING **: 10:03:46.383: Unexpectedly, UWP app `MIGGsrl.VisualizzaFatturaElettronica_3.1.4.0_x86__aydtewdteyzge' (AUMId `MIGGsrl.VisualizzaFatturaElettronica_aydtewdteyzge!it.migg.VisFatt') supports 2 extensions but has no verbs
03/26/2022 10:03:47:INFO:MainApp:Failed to create socket.
Traceback (most recent call last):
  File "C:/msys64\home\mauri\D-Rats-python3_tyw/d_rats/mainapp.py", line 439, in callback_gps
    sock.connect((mapserver_ip, mapserver_port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
03/26/2022 10:03:47:INFO:MainApp:Socket Created
03/26/2022 10:03:47:INFO:StaticGPSSource:StaticGPSPosition: UNKNOWN reporting 45.8005,9.4284@0 ft at 10:03:47
03/26/2022 10:03:47:INFO:MainApp:load main window with self config
03/26/2022 10:03:47:INFO:MessageFolders:_ensure_default_folders []
03/26/2022 10:03:47:INFO:MessageFolders:_ensure_default_folders []
03/26/2022 10:03:47:INFO:MessageFolders:_ensure_default_folders []
03/26/2022 10:03:47:INFO:MessageFolders:_ensure_default_folders []
03/26/2022 10:03:47:INFO:MessageFolders:_ensure_default_folders []
03/26/2022 10:03:47:INFO:LocalFileV:refresh: Adding local file `C:\Users\mauri\OneDrive\Desktop\D-RATS Shared/2021.jpg'
03/26/2022 10:03:47:INFO:LocalFileV:refresh: Adding local file `C:\Users\mauri\OneDrive\Desktop\D-RATS Shared/D-PRS.txt'
03/26/2022 10:03:47:INFO:LocalFileV:refresh: Adding local file `C:\Users\mauri\OneDrive\Desktop\D-RATS Shared/D-PRS_TEST.pdf'
03/26/2022 10:03:47:INFO:LocalFileV:refresh: Adding local file `C:\Users\mauri\OneDrive\Desktop\D-RATS Shared/Hello.txt'
03/26/2022 10:03:47:INFO:LocalFileV:refresh: Adding local file `C:\Users\mauri\OneDrive\Desktop\D-RATS Shared/RATflector_list.txt'
03/26/2022 10:03:47:INFO:LocalFileV:refresh: Adding local file `C:\Users\mauri\OneDrive\Desktop\D-RATS Shared/test.txt'
03/26/2022 10:03:48:INFO:MainApp:connect main window
03/26/2022 10:03:48:INFO:MainApp:connect tabs
03/26/2022 10:03:48:INFO:MainApp:going online
03/26/2022 10:03:48:INFO:D-Rats:main: reloading app

03/26/2022 10:03:48:INFO:MessageRouter:_p: [MR] Starting message router thread
03/26/2022 10:03:48:INFO:MainApp:load the main window
03/26/2022 10:03:48:INFO:MessageRouter:_run_one: Station list was empty
03/26/2022 10:03:48:INFO:MainApp:create map window object-----
03/26/2022 10:03:48:INFO:MapWindow:init MapWindow
03/26/2022 10:03:48:INFO:MainApp:create map window object: connect object-----
03/26/2022 10:03:48:INFO:MainApp:query local gps device to see our current position
03/26/2022 10:03:48:INFO:MapFileSource:Failed to open %s: %s
03/26/2022 10:03:48:INFO:Utils.log_exception:-- Exception: --
Traceback (most recent call last):
  File "C:/msys64\home\mauri\D-Rats-python3_tyw/d_rats/map_sources.py", line 592, in __init__
    input_handle = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/mauri/AppData/Roaming/D-RATS-EV/static_locations/Id.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/msys64\home\mauri\D-Rats-python3_tyw/d_rats/mainapp.py", line 1033, in _load_map_overlays
    source = stype.open_source_by_name(self.config, sname)
  File "C:/msys64\home\mauri\D-Rats-python3_tyw/d_rats/map_sources.py", line 646, in open_source_by_name
    return MapFileSource(name, "Static file", path)
  File "C:/msys64\home\mauri\D-Rats-python3_tyw/d_rats/map_sources.py", line 596, in __init__
    raise MapSourceFailedToConnect(msg)
d_rats.map_sources.MapSourceFailedToConnect: Failed to open C:/Users/mauri/AppData/Roaming/D-RATS-EV/static_locations/Id.csv: [Errno 2] No such file or directory: 'C:/Users/mauri/AppData/Roaming/D-RATS-EV/static_locations/Id.csv'
03/26/2022 10:03:48:INFO:Utils.log_exception:----------------
03/26/2022 10:04:48:INFO:MessageRouter:_run_one: Station list was empty
03/26/2022 10:05:48:INFO:MessageRouter:_run_one: Station list

**Comment by maurizioandreotti** [comment] 2022-03-26 10:43
got back to a starting D-rats just removing file:

C:/Users/mauri/AppData/Roaming/D-RATS-EV/static_locations/Id.csv'

**Comment by maurizioandreotti** [comment] 2022-03-26 10:44
@wb8tyw maybe you just want to know and close this

**Comment by wb8tyw** [comment] 2022-03-26 12:56
D-rats should of handled this better, so this bug should be left open.

A failure to open an overlay file should not have stopped d-rats from connecting, so that it one that we need to find a way to replicate.

The error message also stated that d-rats was told that a file did not exist, when it obviously did exist, since you had to delete it.   And I think d-rats finds the files by a directory lookup,

This sometimes indicates a permission issue with the file, which should not be happening for files in that directory.  It also can indicate that the file is locked by another user having it open.

If this happens again, it would be useful to see what permissions are on the affected file.   We may need both the msys2 permissions and the permissions from the windows properties on the file for the current user.

And the UWP app warning probably should not be  there either.  That one may be hard to isolate.   So far those have been caused by using deprecated GTK/GIO methods.

**Comment by maurizioandreotti** [comment] 2022-03-26 15:44
The file was exisiting but was empty. After deleting It the program got
back reconnecting at startup

Il sab 26 mar 2022, 13:56 John E. Malmberg ***@***.***> ha
scritto:

**Comment by wb8tyw** [comment] 2022-08-27 18:09
This is a duplicate of https://github.com/ham-radio-software/D-Rats/issues/119

**Closed by wb8tyw** 2022-08-27 18:09 UTC
Labels: bug, documentation, duplicate
